name = "dawn-cake-tunne949"
main = "_worker.js"
compatibility_date = "2025-11-04"
keep_vars = true

#[[kv_namespaces]]
#binding = "KV"			#KV绑定名默认不可修改

#id = "5921b03b61f34536bab68c3a614ec724"				#KV数据库id

